
import React,{ useState } from 'react'
import {useNavigate} from 'react-router-dom'
import {preview} from '../assets';
import {getRandomPrompt} from '../utils'
import {FormField,Loader} from '../components'

const CreatePost = () => {
  const navigate = useNavigate();
  const [form,setForm] = useState({
    name:'',
    prompt:'',
    photo:'',
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit=() =>{
    
  }

  const handleChange=(e) =>{
    
  }

  const handleSurpriseMe =() =>{
    
  }
  return (
    <section className="mx-auto max-w-7x">
     <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[600px]'>Create visually stunning images generated by Dall-E</p>
      </div>

      <form className='max-w-3xl mt-16' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            LabelName = 'Your name'
            type ='text'
            name = 'name'
            placeholder = 'John Doe'
            value= {form.name}
            handleChange = {handleChange}
          />
          <FormField
            LabelName = 'Prompt'
            type ='text'
            name = 'Prompt'
            placeholder = 'A plush toy robot sitting against a yellow wall'
            value= {form.prompt}
            handleChange = {handleChange}
            isSurpriseMe
            handleSurpriseMe = {handleSurpriseMe}
          />
        </div>
      </form>
    </section>
  )
}

export default CreatePost